{{- if .Values.connect.create}}
{{- if or (.Values.connect.credentials) (.Values.connect.credentials_base64)  -}}
{{- if and (.Values.connect.credentials) (.Values.connect.credentials_base64) -}}
  {{- fail "Only one of connect.credentials and connect.credentials_base64 can be specified" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connect.credentialsName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connect
    {{- include "onepassword-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.connect.credentialsKey }}: |-
  {{- if (.Values.connect.credentials) }}
  {{ .Values.connect.credentials | b64enc | indent 2 }}
  {{- else }}
  {{ .Values.connect.credentials_base64 | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
