{{- if and (.Values.operator.create) (.Values.operator.token.value) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.operator.token.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "onepassword-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.operator.token.key }}: {{ .Values.operator.token.value }}
{{- end }}
