{{- if (.Values.connect.credentials) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connect.credentialsName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.connect.credentialsKey }}: |-
  {{ .Values.connect.credentials | b64enc | indent 2}}
{{- end }}
