{{- if .Values.operator.roleBinding.create -}}
{{- $name := .Values.operator.roleBinding.name -}}
{{- $clusterRoleName := .Values.operator.clusterRole.name -}}
{{- $serviceAccountName := .Values.operator.serviceAccount.name -}}
{{- range $namespace := .Values.operator.watchNamespace }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}-{{ $namespace }}
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $clusterRoleName}}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}