apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connect.applicationName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onepassword-connect.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.connect.applicationName }}
  ports:
    - port: 8080
      name: {{ .Values.connect.api.name }}
    - port: 8081
      name: {{ .Values.connect.sync.name }}
